services:
  app-dev:
    environment:
      POSTGRES_PRISMA_URL: postgres://yves:${YVES_DB_PASSWORD:?error}@postgres-dev:5432/yves
    build:
      context: .
      target: app-base
    entrypoint:
      - sh
      - -c
    command:
      - ./node_modules/.bin/prisma migrate dev && npm run dev
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src:ro
    depends_on:
      - postgres-dev
    profiles: ["dev"]

  postgres-dev:
    build:
      context: .
      target: db
    environment:
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_INITDB_ARGS: --auth-host=password
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
      YVES_DB_PASSWORD: ${YVES_DB_PASSWORD:?error}
      DEX_DB_PASSWORD: ${DEX_DB_PASSWORD:?error}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    profiles: ["dev"]

  app-prod:
    environment:
      POSTGRES_PRISMA_URL: postgres://yves:${YVES_DB_PASSWORD:?error}@postgres-prod:5432/yves
    image: ghcr.io/mxm-tr/yves:master-app
    env_file:
      - .env.prod
    depends_on:
      - postgres-prod
    profiles: ["prod"]

  postgres-prod:
    image: ghcr.io/mxm-tr/yves:master-db
    environment:
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_INITDB_ARGS: --auth-host=password
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
      YVES_DB_PASSWORD: ${YVES_DB_PASSWORD:?error}
      DEX_DB_PASSWORD: ${DEX_DB_PASSWORD:?error}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    profiles: ["prod"]

volumes:
  postgres_data_dev:
  postgres_data_prod:
