#!/bin/bash
set -ex

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE dex_db;
	CREATE USER dex WITH PASSWORD '$DEX_DB_PASSWORD';
	GRANT ALL PRIVILEGES ON DATABASE dex_db TO dex;
EOSQL