#!/bin/bash
set -ex

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER yves WITH CREATEDB PASSWORD '$YVES_DB_PASSWORD';
	CREATE DATABASE yves;
	GRANT ALL PRIVILEGES ON DATABASE yves TO yves;
EOSQL
